# Generated by Django 3.1.7 on 2021-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_apartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='descriptions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
